Traceback (most recent call last):
  File "/home/goof/anaconda3/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/goof/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/goof/anaconda3/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/goof/anaconda3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/goof/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/goof/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/goof/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
%run hdi_renewables.ipynb
------------------

----- stdout -----
Year                  int64
HDI                 float64
Renewable Energy    float64
dtype: object
   Year    HDI  Renewable Energy
0  1990  0.601         16.662330
2  1991  0.604         16.821274
4  1992  0.607         17.165780
6  1993  0.610         17.209889
8  1994  0.614         17.354901
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
File [0;32m~/anaconda3/lib/python3.11/site-packages/plotly/basedatatypes.py:2327[0m, in [0;36mBaseFigure._validate_get_grid_ref[0;34m(self)[0m
[1;32m   2326[0m     [38;5;28;01mif[39;00m grid_ref [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[0;32m-> 2327[0m         [38;5;28;01mraise[39;00m [38;5;167;01mAttributeError[39;00m([38;5;124m"[39m[38;5;124m_grid_ref[39m[38;5;124m"[39m)
[1;32m   2328[0m [38;5;28;01mexcept[39;00m [38;5;167;01mAttributeError[39;00m:

[0;31mAttributeError[0m: _grid_ref

During handling of the above exception, another exception occurred:

[0;31mException[0m                                 Traceback (most recent call last)
Cell [0;32mIn[8], line 1[0m
[0;32m----> 1[0m get_ipython()[38;5;241m.[39mrun_line_magic([38;5;124m'[39m[38;5;124mrun[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mhdi_renewables.ipynb[39m[38;5;124m'[39m)

File [0;32m~/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py:2456[0m, in [0;36mInteractiveShell.run_line_magic[0;34m(self, magic_name, line, _stack_depth)[0m
[1;32m   2454[0m     kwargs[[38;5;124m'[39m[38;5;124mlocal_ns[39m[38;5;124m'[39m] [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mget_local_scope(stack_depth)
[1;32m   2455[0m [38;5;28;01mwith[39;00m [38;5;28mself[39m[38;5;241m.[39mbuiltin_trap:
[0;32m-> 2456[0m     result [38;5;241m=[39m fn([38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39mkwargs)
[1;32m   2458[0m [38;5;66;03m# The code below prevents the output from being displayed[39;00m
[1;32m   2459[0m [38;5;66;03m# when using magics with decorator @output_can_be_silenced[39;00m
[1;32m   2460[0m [38;5;66;03m# when the last Python token in the expression is a ';'.[39;00m
[1;32m   2461[0m [38;5;28;01mif[39;00m [38;5;28mgetattr[39m(fn, magic[38;5;241m.[39mMAGIC_OUTPUT_CAN_BE_SILENCED, [38;5;28;01mFalse[39;00m):

File [0;32m~/anaconda3/lib/python3.11/site-packages/IPython/core/magics/execution.py:737[0m, in [0;36mExecutionMagics.run[0;34m(self, parameter_s, runner, file_finder)[0m
[1;32m    735[0m     [38;5;28;01mwith[39;00m preserve_keys([38;5;28mself[39m[38;5;241m.[39mshell[38;5;241m.[39muser_ns, [38;5;124m'[39m[38;5;124m__file__[39m[38;5;124m'[39m):
[1;32m    736[0m         [38;5;28mself[39m[38;5;241m.[39mshell[38;5;241m.[39muser_ns[[38;5;124m'[39m[38;5;124m__file__[39m[38;5;124m'[39m] [38;5;241m=[39m filename
[0;32m--> 737[0m         [38;5;28mself[39m[38;5;241m.[39mshell[38;5;241m.[39msafe_execfile_ipy(filename, raise_exceptions[38;5;241m=[39m[38;5;28;01mTrue[39;00m)
[1;32m    738[0m     [38;5;28;01mreturn[39;00m
[1;32m    740[0m [38;5;66;03m# Control the response to exit() calls made by the script being run[39;00m

File [0;32m~/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py:2981[0m, in [0;36mInteractiveShell.safe_execfile_ipy[0;34m(self, fname, shell_futures, raise_exceptions)[0m
[1;32m   2979[0m result [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mrun_cell(cell, silent[38;5;241m=[39m[38;5;28;01mTrue[39;00m, shell_futures[38;5;241m=[39mshell_futures)
[1;32m   2980[0m [38;5;28;01mif[39;00m raise_exceptions:
[0;32m-> 2981[0m     result[38;5;241m.[39mraise_error()
[1;32m   2982[0m [38;5;28;01melif[39;00m [38;5;129;01mnot[39;00m result[38;5;241m.[39msuccess:
[1;32m   2983[0m     [38;5;28;01mbreak[39;00m

File [0;32m~/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py:294[0m, in [0;36mExecutionResult.raise_error[0;34m(self)[0m
[1;32m    292[0m     [38;5;28;01mraise[39;00m [38;5;28mself[39m[38;5;241m.[39merror_before_exec
[1;32m    293[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39merror_in_exec [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[0;32m--> 294[0m     [38;5;28;01mraise[39;00m [38;5;28mself[39m[38;5;241m.[39merror_in_exec

    [0;31m[... skipping hidden 1 frame][0m

File [0;32m/tmp/ipykernel_62239/4214927715.py:22[0m
[1;32m     20[0m plt[38;5;241m.[39mxlabel([38;5;124m'[39m[38;5;124mYear[39m[38;5;124m'[39m)
[1;32m     21[0m plt[38;5;241m.[39mylabel([38;5;124m'[39m[38;5;124mValue[39m[38;5;124m'[39m)
[0;32m---> 22[0m fig[38;5;241m.[39mupdate_yaxes(title_text[38;5;241m=[39m[38;5;124m"[39m[38;5;124m<b>primary</b> yaxis title[39m[38;5;124m"[39m, secondary_y[38;5;241m=[39m[38;5;28;01mFalse[39;00m)
[1;32m     23[0m fig[38;5;241m.[39mupdate_yaxes(title_text[38;5;241m=[39m[38;5;124m"[39m[38;5;124m<b>secondary</b> yaxis title[39m[38;5;124m"[39m, secondary_y[38;5;241m=[39m[38;5;28;01mTrue[39;00m)
[1;32m     25[0m plt[38;5;241m.[39mlegend()

File [0;32m~/anaconda3/lib/python3.11/site-packages/plotly/graph_objs/_figure.py:21566[0m, in [0;36mFigure.update_yaxes[0;34m(self, patch, selector, overwrite, row, col, secondary_y, **kwargs)[0m
[1;32m  21506[0m [38;5;28;01mdef[39;00m [38;5;21mupdate_yaxes[39m(
[1;32m  21507[0m     [38;5;28mself[39m,
[1;32m  21508[0m     patch[38;5;241m=[39m[38;5;28;01mNone[39;00m,
[0;32m   (...)[0m
[1;32m  21514[0m     [38;5;241m*[39m[38;5;241m*[39mkwargs,
[1;32m  21515[0m ) [38;5;241m-[39m[38;5;241m>[39m [38;5;124m"[39m[38;5;124mFigure[39m[38;5;124m"[39m:
[1;32m  21516[0m [38;5;250m    [39m[38;5;124;03m"""[39;00m
[1;32m  21517[0m [38;5;124;03m    Perform a property update operation on all yaxis objects[39;00m
[1;32m  21518[0m [38;5;124;03m    that satisfy the specified selection criteria[39;00m
[0;32m   (...)[0m
[1;32m  21564[0m [38;5;124;03m        Returns the Figure object that the method was called on[39;00m
[1;32m  21565[0m [38;5;124;03m    """[39;00m
[0;32m> 21566[0m     [38;5;28;01mfor[39;00m obj [38;5;129;01min[39;00m [38;5;28mself[39m[38;5;241m.[39mselect_yaxes(
[1;32m  21567[0m         selector[38;5;241m=[39mselector, row[38;5;241m=[39mrow, col[38;5;241m=[39mcol, secondary_y[38;5;241m=[39msecondary_y
[1;32m  21568[0m     ):
[1;32m  21569[0m         obj[38;5;241m.[39mupdate(patch, overwrite[38;5;241m=[39moverwrite, [38;5;241m*[39m[38;5;241m*[39mkwargs)
[1;32m  21571[0m     [38;5;28;01mreturn[39;00m [38;5;28mself[39m

File [0;32m~/anaconda3/lib/python3.11/site-packages/plotly/graph_objs/_figure.py:21452[0m, in [0;36mFigure.select_yaxes[0;34m(self, selector, row, col, secondary_y)[0m
[1;32m  21410[0m [38;5;28;01mdef[39;00m [38;5;21mselect_yaxes[39m([38;5;28mself[39m, selector[38;5;241m=[39m[38;5;28;01mNone[39;00m, row[38;5;241m=[39m[38;5;28;01mNone[39;00m, col[38;5;241m=[39m[38;5;28;01mNone[39;00m, secondary_y[38;5;241m=[39m[38;5;28;01mNone[39;00m):
[1;32m  21411[0m [38;5;250m    [39m[38;5;124;03m"""[39;00m
[1;32m  21412[0m [38;5;124;03m    Select yaxis subplot objects from a particular subplot cell[39;00m
[1;32m  21413[0m [38;5;124;03m    and/or yaxis subplot objects that satisfy custom selection[39;00m
[0;32m   (...)[0m
[1;32m  21449[0m [38;5;124;03m        objects that satisfy all of the specified selection criteria[39;00m
[1;32m  21450[0m [38;5;124;03m    """[39;00m
[0;32m> 21452[0m     [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_select_layout_subplots_by_prefix(
[1;32m  21453[0m         [38;5;124m"[39m[38;5;124myaxis[39m[38;5;124m"[39m, selector, row, col, secondary_y[38;5;241m=[39msecondary_y
[1;32m  21454[0m     )

File [0;32m~/anaconda3/lib/python3.11/site-packages/plotly/basedatatypes.py:1414[0m, in [0;36mBaseFigure._select_layout_subplots_by_prefix[0;34m(self, prefix, selector, row, col, secondary_y)[0m
[1;32m   1407[0m [38;5;250m[39m[38;5;124;03m"""[39;00m
[1;32m   1408[0m [38;5;124;03mHelper called by code generated select_* methods[39;00m
[1;32m   1409[0m [38;5;124;03m"""[39;00m
[1;32m   1411[0m [38;5;28;01mif[39;00m row [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m [38;5;129;01mor[39;00m col [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m [38;5;129;01mor[39;00m secondary_y [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[1;32m   1412[0m     [38;5;66;03m# Build mapping from container keys ('xaxis2', 'scene4', etc.)[39;00m
[1;32m   1413[0m     [38;5;66;03m# to (row, col, secondary_y) triplets[39;00m
[0;32m-> 1414[0m     grid_ref [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_validate_get_grid_ref()
[1;32m   1415[0m     container_to_row_col [38;5;241m=[39m {}
[1;32m   1416[0m     [38;5;28;01mfor[39;00m r, subplot_row [38;5;129;01min[39;00m [38;5;28menumerate[39m(grid_ref):

File [0;32m~/anaconda3/lib/python3.11/site-packages/plotly/basedatatypes.py:2329[0m, in [0;36mBaseFigure._validate_get_grid_ref[0;34m(self)[0m
[1;32m   2327[0m         [38;5;28;01mraise[39;00m [38;5;167;01mAttributeError[39;00m([38;5;124m"[39m[38;5;124m_grid_ref[39m[38;5;124m"[39m)
[1;32m   2328[0m [38;5;28;01mexcept[39;00m [38;5;167;01mAttributeError[39;00m:
[0;32m-> 2329[0m     [38;5;28;01mraise[39;00m [38;5;167;01mException[39;00m(
[1;32m   2330[0m         [38;5;124m"[39m[38;5;124mIn order to reference traces by row and column, [39m[38;5;124m"[39m
[1;32m   2331[0m         [38;5;124m"[39m[38;5;124myou must first use [39m[38;5;124m"[39m
[1;32m   2332[0m         [38;5;124m"[39m[38;5;124mplotly.tools.make_subplots [39m[38;5;124m"[39m
[1;32m   2333[0m         [38;5;124m"[39m[38;5;124mto create the figure with a subplot grid.[39m[38;5;124m"[39m
[1;32m   2334[0m     )
[1;32m   2335[0m [38;5;28;01mreturn[39;00m grid_ref

[0;31mException[0m: In order to reference traces by row and column, you must first use plotly.tools.make_subplots to create the figure with a subplot grid.

